version: "3.8"

services:
  myfin-api:
    container_name: myfin-api
    build:
      context: ./ # path to your backend folder
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:3001"
    env_file:
      - .env  
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 5s
      retries: 3
